# Generated by Django 5.2.15 on 2026-06-15 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0003_add_error_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conflictpair',
            name='error_types',
            field=models.JSONField(blank=True, default=list, help_text='EvidenceLens error taxonomy: overgeneralization, condition_dropping, false_certainty, missing_evidence, unsupported_claim, wrong_evidence, missing_limitation, contradiction_with_source, conflict_ignored, paper_section_misread'),
        ),
    ]
