# Generated by Django 5.2.15 on 2026-07-02 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0006_alter_answerrecord_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=64)),
                ('iteration', models.IntegerField(default=0)),
                ('role', models.CharField(choices=[('thought', 'Thought'), ('action', 'Action'), ('observation', 'Observation'), ('answer', 'Answer'), ('error', 'Error')], max_length=20)),
                ('tool_name', models.CharField(choices=[('retrieve_answers', 'Retrieve'), ('nli_score', 'Nli'), ('llm_call', 'Llm'), ('confidence_gate', 'Threshold'), ('none', 'None')], default='none', max_length=30)),
                ('tool_input', models.JSONField(default=dict)),
                ('tool_output', models.JSONField(default=dict)),
                ('model_version', models.CharField(blank=True, max_length=100)),
                ('latency_ms', models.IntegerField(null=True)),
                ('prompt_tokens', models.IntegerField(null=True)),
                ('final_answer', models.TextField(blank=True)),
                ('confidence', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traces', to='evidence.analysisjob')),
            ],
            options={
                'ordering': ['session_id', 'iteration'],
            },
        ),
    ]
